spring:
  application:
    name: fhir-integration-service

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true

fhir:
  server:
    base-url: http://localhost:8080/fhir
